version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: lostmedia
      POSTGRES_PASSWORD: lostmedia123
      POSTGRES_DB: lostmedia
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      SESSION_SECRET: supersecretkey
      DATABASE_URL: postgres://lostmedia:lostmedia123@db:5432/lostmedia
      NEXT_PUBLIC_BACKEND_URL: http://localhost:5000
    depends_on:
      - db
    command: npm run dev

volumes:
  pgdata: 